/*
 * SPDX-FileCopyrightText: (C) 2013-2022 Daniel Nicoletti <dantti12@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef COMMON_H
#define COMMON_H

#include <QtCore/QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(CUTELYST_DISPATCHER)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_DISPATCHER_PATH)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_DISPATCHER_CHAINED)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_CONTROLLER)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_CORE)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_ENGINE)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_UPLOAD)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_MULTIPART)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_VIEW)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_REQUEST)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_RESPONSE)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_STATS)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_COMPONENT)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_UTILS_AUTH)
Q_DECLARE_LOGGING_CATEGORY(CUTELYST_ASYNC)

#endif // COMMON_H
